### ISSUE TITLE
Sylwetki partnerów społecznościowych z bloga?

### ISSUE THREAD

**Issue by MarcinKosinski** [whyRconf/book#30]
Co myślicie na ten temat?

**Comment by AleksandraDabrowska** [comment]
Może warto dodać też sylwetki organizatorów?

**Comment by MarcinKosinski** [comment]
Nie mamy tekstów gotowych. A do partnerów mamy na blogu. Zajmę się tym dziś, bo muszę wysłać do północy książkę do drukarni.

**Comment by AleksandraDabrowska** [comment]
Chodzilo np o politechnike czy MI2 ale nie wszyscy maja opisy.
W ciągu 1h dodamy opisy partnerów.

**Comment by AleksandraDabrowska** [comment]
@MarcinKosinski , nie wszyscy partnerzy ze strony mają swoją sylwetkę na blogu. Co mamy z tym zrobić?

**Comment by MarcinKosinski** [comment]
@AleksandraDabrowska ok rozumiem teraz. Mozna wziac opis MiNI PW z naszej strony whyr.pl z sekcji Miejsce. Co do partnerow bez opisow - wystarczy wtedy samo logo z brakiem opisu.

Mamy 100 miejsc w ksiazce tak czy siak. Czy bedziemy mieli 70 stron czy 90 czy 5 to placimy za to wszystko tyle samo. Dzieki za pomoc.

**Comment by MarcinKosinski** [comment]
Świetna robota @agosiewska @AleksandraDabrowska  ! Brzytwa!
