### ISSUE TITLE
W planie konferencji podpisac przerwy kawowe i lunche nazwami sponsorow

### ISSUE THREAD

**Issue by MarcinKosinski** [whyRconf/book#34]

**Comment by MarcinKosinski** [comment]
Jak tu

![image](https://user-images.githubusercontent.com/6773454/30346550-66a81664-9809-11e7-95af-d5802a91295e.png)

**Comment by AleksandraDabrowska** [comment]
plan będzie dziś wieczorem (ok. 20)
