### ISSUE TITLE
Sesje: PwC, Społeczności

### ISSUE THREAD

**Issue by AleksandraDabrowska** [whyRconf/book#8]
Jest już jakaś ustalona kolejność w tych sesjach + wykłady

**Comment by MarcinKosinski** [comment]
@AleksandraDabrowska sesja spolecznosci to jeden panel dyskusyjny
a sesja PwC ma kolejnosc jak tutaj http://whyr.pl/plan/

![image](https://user-images.githubusercontent.com/6773454/30038443-eb55166e-91c4-11e7-8ece-babf3211b0e6.png)
